const cars = [
  {
    id: 1,
    name: "Toyoooota1 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 2,
    name: "Toyooota2 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 3,
    name: "Toyoota3 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 4,
    name: "Toyota4 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 5,
    name: "Toyota5 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 6,
    name: "Toyota6 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 7,
    name: "Toyota7 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 8,
    name: "Toyota8 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 9,
    name: "Toyota9 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 10,
    name: "Toyota10 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 11,
    name: "Toyota11 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 12,
    name: "Toyota12 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 13,
    name: "Toyota13 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 14,
    name: "Toyota14 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 15,
    name: "Toyota15 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 16,
    name: "Toyota16 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 17,
    name: "Toyota17 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 18,
    name: "Toyota18 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 19,
    name: "Toyota19 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 20,
    name: "Toyota20 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 21,
    name: "Toyota21 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 22,
    name: "Toyota22 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 23,
    name: "Toyota23 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 24,
    name: "Toyota24 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 25,
    name: "Toyota25 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 26,
    name: "Toyota26 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 27,
    name: "Toyota27 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 28,
    name: "Toyota28 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 29,
    name: "Toyota29 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 30,
    name: "Toyota30 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 31,
    name: "Toyota31 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 32,
    name: "Toyota32 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 33,
    name: "Toyota33 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 34,
    name: "Toyota34 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 35,
    name: "Toyota35 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 36,
    name: "Toyota36 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 37,
    name: "Toyota37 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 38,
    name: "Toyota38 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 39,
    name: "Toyota39 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 40,
    name: "Toyota40 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 41,
    name: "Toyota41 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 42,
    name: "Toyota42 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 43,
    name: "Toyota43 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 44,
    name: "Toyota44 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 45,
    name: "Toyota45 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 46,
    name: "Toyota46 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 47,
    name: "Toyota47 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 48,
    name: "Toyota48 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 49,
    name: "Toyota49 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 50,
    name: "Toyota50 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 51,
    name: "Toyota51 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 52,
    name: "Toyota52 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 53,
    name: "Toyota53 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 54,
    name: "Toyota54 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 55,
    name: "Toyota55 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 56,
    name: "Toyota56 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 57,
    name: "Toyota57 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 58,
    name: "Toyota58 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 59,
    name: "Toyota59 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 60,
    name: "Toyota60 RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
];

export default cars;
