
const cars = [
  {
    id: 1,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Toyota RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id: 2,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Honda Civic",
    people: "5",
    fuel: "Petrol",
    mileage: "7.2",
    drive: "Manual",
    year: "2020",
    price: "$350",
  },
  {
    id: 3,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Ford Escape",
    people: "4",
    fuel: "Hybrid",
    mileage: "5.5",
    drive: "Automatic",
    year: "2022",
    price: "$500",
  },
  {
    id: 4,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Nissan Altima",
    people: "5",
    fuel: "Petrol",
    mileage: "7.0",
    drive: "Automatic",
    year: "2021",
    price: "$380",
  },
  {
    id: 5,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Chevrolet Malibu",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.8",
    drive: "Automatic",
    year: "2022",
    price: "$520",
  },
  {
    id: 6,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Mazda CX-5",
    people: "5",
    fuel: "Petrol",
    mileage: "6.5",
    drive: "Automatic",
    year: "2020",
    price: "$400",
  },
  {
    id: 7,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Kia Sportage",
    people: "5",
    fuel: "Diesel",
    mileage: "6.2",
    drive: "Manual",
    year: "2021",
    price: "$420",
  },
  {
    id: 8,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Hyundai Tucson",
    people: "5",
    fuel: "Petrol",
    mileage: "7.5",
    drive: "Automatic",
    year: "2022",
    price: "$460",
  },
  {
    id: 9,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Subaru Outback",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.7",
    drive: "Automatic",
    year: "2021",
    price: "$490",
  },
  {
    id: 10,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Volkswagen Tiguan",
    people: "5",
    fuel: "Petrol",
    mileage: "7.3",
    drive: "Automatic",
    year: "2020",
    price: "$370",
  },
  {
    id: 11,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Audi Q5",
    people: "5",
    fuel: "Hybrid",
    mileage: "6.0",
    drive: "Automatic",
    year: "2022",
    price: "$540",
  },
  {
    id: 12,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "BMW X3",
    people: "5",
    fuel: "Petrol",
    mileage: "7.1",
    drive: "Automatic",
    year: "2021",
    price: "$480",
  },
  {
    id: 13,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Mercedes-Benz GLC",
    people: "5",
    fuel: "Diesel",
    mileage: "6.3",
    drive: "Automatic",
    year: "2020",
    price: "$550",
  },
  {
    id: 14,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Lexus RX",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.9",
    drive: "Automatic",
    year: "2022",
    price: "$560",
  },
  {
    id: 15,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Jeep Cherokee",
    people: "5",
    fuel: "Petrol",
    mileage: "6.9",
    drive: "Automatic",
    year: "2021",
    price: "$450",
  },
  {
    id: 16,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Tesla Model 3",
    people: "5",
    fuel: "Electric",
    mileage: "3.5",
    drive: "Automatic",
    year: "2022",
    price: "$600",
  },
  {
    id: 17,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Acura MDX",
    people: "5",
    fuel: "Hybrid",
    mileage: "6.2",
    drive: "Automatic",
    year: "2020",
    price: "$520",
  },
  {
    id: 18,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "GMC Acadia",
    people: "5",
    fuel: "Petrol",
    mileage: "7.4",
    drive: "Automatic",
    year: "2021",
    price: "$470",
  },
  {
    id: 19,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Volvo XC60",
    people: "5",
    fuel: "Hybrid",
    mileage: "6.4",
    drive: "Automatic",
    year: "2022",
    price: "$580",
  },
  {
    id: 20,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Land Rover Discovery",
    people: "5",
    fuel: "Diesel",
    mileage: "6.7",
    drive: "Automatic",
    year: "2021",
    price: "$490",
  },
  {
    id: 21,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Porsche Cayenne",
    people: "5",
    fuel: "Petrol",
    mileage: "7.6",
    drive: "Automatic",
    year: "2020",
    price: "$550",
  },
  {
    id: 22,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Subaru Forester",
    people: "5",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2022",
    price: "$540",
  },
  {
    id: 23,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Ford Explorer",
    people: "5",
    fuel: "Petrol",
    mileage: "7.8",
    drive: "Automatic",
    year: "2021",
    price: "$470",
  },
  {
    id: 24,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Chevrolet Equinox",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.5",
    drive: "Automatic",
    year: "2020",
    price: "$510",
  },
  {
    id: 25,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Nissan Rogue",
    people: "5",
    fuel: "Petrol",
    mileage: "7.2",
    drive: "Automatic",
    year: "2022",
    price: "$490",
  },
  {
    id: 26,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Jeep Wrangler",
    people: "4",
    fuel: "Petrol",
    mileage: "6.7",
    drive: "Manual",
    year: "2021",
    price: "$420",
  },
  {
    id: 27,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Toyota Corolla",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.9",
    drive: "Automatic",
    year: "2020",
    price: "$400",
  },
  {
    id: 28,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Nissan Rogue",
    people: "5",
    fuel: "Petrol",
    mileage: "7.2",
    drive: "Automatic",
    year: "2022",
    price: "$490",
  },
  {
    id: 29,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Jeep Wrangler",
    people: "4",
    fuel: "Petrol",
    mileage: "6.7",
    drive: "Manual",
    year: "2021",
    price: "$420",
  },
  {
    id: 30,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Toyota Corolla",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.9",
    drive: "Automatic",
    year: "2020",
    price: "$400",
  },
  {
    id: 31,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Toyota RAV4",
    people: "4",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2021",
    price: "$440",
  },
  {
    id:32,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Honda Civic",
    people: "5",
    fuel: "Petrol",
    mileage: "7.2",
    drive: "Manual",
    year: "2020",
    price: "$350",
  },
  {
    id: 33,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Ford Escape",
    people: "4",
    fuel: "Hybrid",
    mileage: "5.5",
    drive: "Automatic",
    year: "2022",
    price: "$500",
  },
  {
    id: 34,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Nissan Altima",
    people: "5",
    fuel: "Petrol",
    mileage: "7.0",
    drive: "Automatic",
    year: "2021",
    price: "$380",
  },
  {
    id: 35,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Chevrolet Malibu",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.8",
    drive: "Automatic",
    year: "2022",
    price: "$520",
  },
  {
    id: 36,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Mazda CX-5",
    people: "5",
    fuel: "Petrol",
    mileage: "6.5",
    drive: "Automatic",
    year: "2020",
    price: "$400",
  },
  {
    id: 37,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Kia Sportage",
    people: "5",
    fuel: "Diesel",
    mileage: "6.2",
    drive: "Manual",
    year: "2021",
    price: "$420",
  },
  {
    id: 38,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Hyundai Tucson",
    people: "5",
    fuel: "Petrol",
    mileage: "7.5",
    drive: "Automatic",
    year: "2022",
    price: "$460",
  },
  {
    id: 39,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Subaru Outback",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.7",
    drive: "Automatic",
    year: "2021",
    price: "$490",
  },
  {
    id: 40,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Volkswagen Tiguan",
    people: "5",
    fuel: "Petrol",
    mileage: "7.3",
    drive: "Automatic",
    year: "2020",
    price: "$370",
  },
  {
    id: 41,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Audi Q5",
    people: "5",
    fuel: "Hybrid",
    mileage: "6.0",
    drive: "Automatic",
    year: "2022",
    price: "$540",
  },
  {
    id: 42,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "BMW X3",
    people: "5",
    fuel: "Petrol",
    mileage: "7.1",
    drive: "Automatic",
    year: "2021",
    price: "$480",
  },
  {
    id: 43,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Mercedes-Benz GLC",
    people: "5",
    fuel: "Diesel",
    mileage: "6.3",
    drive: "Automatic",
    year: "2020",
    price: "$550",
  },
  {
    id: 44,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Lexus RX",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.9",
    drive: "Automatic",
    year: "2022",
    price: "$560",
  },
  {
    id: 45,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Jeep Cherokee",
    people: "5",
    fuel: "Petrol",
    mileage: "6.9",
    drive: "Automatic",
    year: "2021",
    price: "$450",
  },
  {
    id: 46,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Tesla Model 3",
    people: "5",
    fuel: "Electric",
    mileage: "3.5",
    drive: "Automatic",
    year: "2022",
    price: "$600",
  },
  {
    id: 47,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Acura MDX",
    people: "5",
    fuel: "Hybrid",
    mileage: "6.2",
    drive: "Automatic",
    year: "2020",
    price: "$520",
  },
  {
    id: 48,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "GMC Acadia",
    people: "5",
    fuel: "Petrol",
    mileage: "7.4",
    drive: "Automatic",
    year: "2021",
    price: "$470",
  },
  {
    id: 49,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Volvo XC60",
    people: "5",
    fuel: "Hybrid",
    mileage: "6.4",
    drive: "Automatic",
    year: "2022",
    price: "$580",
  },
  {
    id: 50,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Land Rover Discovery",
    people: "5",
    fuel: "Diesel",
    mileage: "6.7",
    drive: "Automatic",
    year: "2021",
    price: "$490",
  },
  {
    id: 51,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Porsche Cayenne",
    people: "5",
    fuel: "Petrol",
    mileage: "7.6",
    drive: "Automatic",
    year: "2020",
    price: "$550",
  },
  {
    id: 52,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Subaru Forester",
    people: "5",
    fuel: "Hybrid",
    mileage: "6.1",
    drive: "Automatic",
    year: "2022",
    price: "$540",
  },
  {
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    id: 53,
    name: "Ford Explorer",
    people: "5",
    fuel: "Petrol",
    mileage: "7.8",
    drive: "Automatic",
    year: "2021",
    price: "$470",
  },
  {
    id: 54,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Chevrolet Equinox",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.5",
    drive: "Automatic",
    year: "2020",
    price: "$510",
  },
  {
    id: 55,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Nissan Rogue",
    people: "5",
    fuel: "Petrol",
    mileage: "7.2",
    drive: "Automatic",
    year: "2022",
    price: "$490",
  },
  {
    id: 56,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Jeep Wrangler",
    people: "4",
    fuel: "Petrol",
    mileage: "6.7",
    drive: "Manual",
    year: "2021",
    price: "$420",
  },
  {
    id: 57,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Toyota Corolla",
    people: "5",
    fuel: "Hybrid",
    mileage: "5.9",
    drive: "Automatic",
    year: "2020",
    price: "$400",
  },
  {
    id: 58,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Mercedes-Benz GLE",
    people: "5",
    fuel: "Diesel",
    mileage: "6.6",
    drive: "Automatic",
    year: "2021",
    price: "$520",
  },
  {
    id: 59,
    img:'https://img.freepik.com/premium-photo/modern-automobile-classic-technology-wheel-traffic_665346-119.jpg',
    name: "Porsche 911",
    people: "2",
    fuel: "Petrol",
    mileage: "9.0",
    drive: "Automatic",
    year: "2020",
    price: "$800",
  },
  {
    id: 60,
    img:'https://img.freepik.com/free-photo/view-car-running-high-speed_23-2150635406.jpg',
    name: "Audi A4",
    people: "5",
    fuel: "Petrol",
    mileage: "7.5",
    drive: "Automatic",
    year: "2021",
    price: "$420",
  },
];

export default cars;
